# Generated by Django 3.2 on 2021-07-17 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth_user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='auth_user',
            name='password',
        ),
    ]
