# Generated by Django 3.2 on 2021-07-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_delete_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='rol',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
