# Generated by Django 3.2 on 2021-07-26 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20210725_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni_trabajador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.trabajador'),
        ),
    ]
